### ISSUE TITLE
Wrong mapping in entity

### ISSUE THREAD

**Issue by smilesrg** [fsi-open/demo#12] opened 2014-11-28 13:56 UTC
When I;m trying to set up project manually (without using vagrant), the error appears:

```
D:\Development\Projects\fsi-demo>php app/console doctrine:fixtures:load
Careful, database will be purged. Do you want to continue Y/N ?y
  > purging database
  > loading FSi\Bundle\AdminDemoBundle\DataFixtures\ORM\LoadUserData



  [FSi\DoctrineExtensions\Uploadable\Exception\MappingException]
  There are wrong mappings in xml mapping for class "FOS\UserBundle\Entity\User" in file "D:\Development\Projects\fsi-demo\vendor\friendsofsymfony\user-bundle\FOS\UserBundle\Resources\config\doctrine/User.orm.xml"
```

BTW maybe it's related to this issue? https://github.com/fsi-open/doctrine-extensions-bundle/issues/26

**Comment by bartekgruszka** [comment] 2015-02-02 15:40
I think it's not a bug in any fsi-open project but in a doctrine. Note Windows and last slash in the exception message: `..\config\doctrine/User.orm.xml`.

Solution: https://github.com/doctrine/common/pull/352

**Comment by szymach** [comment] 2017-06-09 09:32
Closing as part of cleanup, as this bundle is abandonded.

**Closed by szymach** 2017-06-09 09:32 UTC
